# Generated by Django 5.0.1 on 2024-01-20 21:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('famille', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Bon_Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255)),
                ('sphere_d', models.FloatField()),
                ('cylindre_d', models.FloatField()),
                ('axe_d', models.FloatField()),
                ('quatite_d', models.IntegerField()),
                ('sphere_g', models.FloatField()),
                ('cylindre_g', models.FloatField()),
                ('axe_g', models.FloatField()),
                ('quatite_g', models.IntegerField()),
                ('date_de_bl', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categorie_d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_d', to='sherly_app.famille')),
                ('categorie_g', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_g', to='sherly_app.famille')),
                ('produit_d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_d', to='sherly_app.produit')),
                ('produit_g', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_g', to='sherly_app.produit')),
            ],
        ),
    ]
