# Generated by Django 5.0.1 on 2024-01-20 23:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherly_app', '0002_bon_commande_no_cmde'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bon_commande',
            old_name='date_de_bl',
            new_name='date_de_cmd',
        ),
        migrations.CreateModel(
            name='Bon_Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_de_bon', models.DateTimeField(default=django.utils.timezone.now)),
                ('bon_commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bon_livraison', to='sherly_app.bon_commande')),
            ],
        ),
    ]
