# Generated by Django 5.0.1 on 2024-01-20 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherly_app', '0003_rename_date_de_bl_bon_commande_date_de_cmd_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bon_livraison',
            old_name='date_de_bon',
            new_name='date_de_bl',
        ),
    ]
