# Generated by Django 5.0.1 on 2024-01-21 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherly_app', '0004_rename_date_de_bon_bon_livraison_date_de_bl'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='conditionnement_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='produit',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
