# Generated by Django 5.0.1 on 2024-01-21 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherly_app', '0005_produit_conditionnement_count_produit_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='famille',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sherly_app.famille'),
        ),
    ]
