# Generated by Django 5.0.1 on 2024-01-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherly_app', '0014_bon_livraison_no_bl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom1', models.CharField(blank=True, max_length=255, null=True)),
                ('nom2', models.CharField(blank=True, max_length=255, null=True)),
                ('ligne1', models.CharField(blank=True, max_length=255, null=True)),
                ('ligne2', models.CharField(blank=True, max_length=255, null=True)),
                ('ligne3', models.CharField(blank=True, max_length=255, null=True)),
                ('ligne4', models.CharField(blank=True, max_length=255, null=True)),
                ('ligne', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
