# Generated by Django 5.0.1 on 2024-01-22 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherly_app', '0015_societe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='societe',
            old_name='ligne',
            new_name='ligne5',
        ),
    ]
