# Generated by Django 5.0.1 on 2024-01-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherly_app', '0017_bon_livraison_achteur1_bon_livraison_achteur2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='societe',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='societe',
            name='ligne1',
            field=models.CharField(blank=True, default='AV Naciones Unidas', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='societe',
            name='ligne2',
            field=models.CharField(blank=True, default='Ed Cristamar 30,', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='societe',
            name='ligne3',
            field=models.CharField(blank=True, default='Peurto Banus 29660,', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='societe',
            name='ligne4',
            field=models.CharField(blank=True, default='Mail: admin@gmail.com', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='societe',
            name='ligne5',
            field=models.CharField(blank=True, default='Numero IVA: ESB06835052', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='societe',
            name='nom1',
            field=models.CharField(blank=True, default='SHERLY & STRATEGY SL', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='societe',
            name='nom2',
            field=models.CharField(blank=True, default='Division Optical', max_length=255, null=True),
        ),
    ]
