# Generated by Django 5.0.1 on 2024-01-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherly_app', '0018_societe_logo_alter_societe_ligne1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='societe',
            name='code_client',
            field=models.CharField(default='00033147853314', max_length=255),
        ),
    ]
