# Generated by Django 5.0.1 on 2024-01-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherly_app', '0020_remove_produit_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='reference',
            field=models.CharField(default='', editable=False, max_length=7),
        ),
    ]
