# Generated by Django 5.0.1 on 2024-01-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherly_app', '0021_produit_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bon_livraison',
            name='achteur1',
        ),
        migrations.RemoveField(
            model_name='bon_livraison',
            name='achteur2',
        ),
        migrations.RemoveField(
            model_name='bon_livraison',
            name='achteur3',
        ),
        migrations.RemoveField(
            model_name='bon_livraison',
            name='achteur4',
        ),
        migrations.RemoveField(
            model_name='bon_livraison',
            name='achteur5',
        ),
        migrations.RemoveField(
            model_name='bon_livraison',
            name='achteur6',
        ),
        migrations.RemoveField(
            model_name='bon_livraison',
            name='livre1',
        ),
        migrations.RemoveField(
            model_name='bon_livraison',
            name='livre2',
        ),
        migrations.RemoveField(
            model_name='bon_livraison',
            name='livre3',
        ),
        migrations.RemoveField(
            model_name='bon_livraison',
            name='livre4',
        ),
        migrations.AddField(
            model_name='societe',
            name='achteur1',
            field=models.CharField(default='SCROTIS  OPTIC 2000 ', max_length=50),
        ),
        migrations.AddField(
            model_name='societe',
            name='achteur2',
            field=models.CharField(default='38 rue Saint Denis', max_length=50),
        ),
        migrations.AddField(
            model_name='societe',
            name='achteur3',
            field=models.CharField(default='92700 COLOMBES', max_length=50),
        ),
        migrations.AddField(
            model_name='societe',
            name='achteur4',
            field=models.CharField(default='FRANCE', max_length=50),
        ),
        migrations.AddField(
            model_name='societe',
            name='achteur5',
            field=models.CharField(default='Numero TVA Intraceo', max_length=50),
        ),
        migrations.AddField(
            model_name='societe',
            name='achteur6',
            field=models.CharField(default='FR7547911891', max_length=50),
        ),
        migrations.AddField(
            model_name='societe',
            name='livre1',
            field=models.CharField(default='SCROTIS  OPTIC 2000', max_length=50),
        ),
        migrations.AddField(
            model_name='societe',
            name='livre2',
            field=models.CharField(default='38 rue Saint Denis', max_length=50),
        ),
        migrations.AddField(
            model_name='societe',
            name='livre3',
            field=models.CharField(default='92700 COLOMBES', max_length=50),
        ),
        migrations.AddField(
            model_name='societe',
            name='livre4',
            field=models.CharField(default='FRANCE', max_length=50),
        ),
    ]
