# Generated by Django 5.0.1 on 2024-01-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherly_app', '0022_remove_bon_livraison_achteur1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='societe',
            name='nif',
            field=models.CharField(default='NIF:B062835052 № IVA : ESB068350052', max_length=100),
        ),
        migrations.AddField(
            model_name='societe',
            name='phrase',
            field=models.CharField(default="L'expédition s'effectue conformément a nos conditions générales de vente", max_length=100),
        ),
    ]
