# Generated by Django 5.0.1 on 2024-01-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherly_app', '0024_famille_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
