# Generated by Django 5.0.1 on 2024-01-27 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherly_app', '0025_produit_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bon_commande',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
