# Generated by Django 5.0.1 on 2024-01-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherly_app', '0026_bon_commande_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societe',
            name='nif',
            field=models.CharField(default='', max_length=100),
        ),
    ]
