# Generated by Django 5.0.1 on 2024-01-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherly_app', '0027_alter_societe_nif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societe',
            name='nif',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
