# Generated by Django 4.2.9 on 2024-01-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherly_app', '0028_alter_societe_nif'),
    ]

    operations = [
        migrations.AddField(
            model_name='bon_livraison',
            name='emailed',
            field=models.BooleanField(default=False),
        ),
    ]
