# Generated by Django 4.2.9 on 2024-01-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherly_app', '0029_bon_livraison_emailed'),
    ]

    operations = [
        migrations.AddField(
            model_name='societe',
            name='boite_envoi',
            field=models.EmailField(default='optiquejaures@hotmail.com', max_length=100),
        ),
        migrations.AddField(
            model_name='societe',
            name='boite_reception',
            field=models.EmailField(default='gestionrecrutement@hotmail.com', max_length=100),
        ),
    ]
