# Generated by Django 4.2.9 on 2024-02-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherly_app', '0032_alter_societe_boite_envoi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bon_commande',
            name='axe_d',
            field=models.IntegerField(),
        ),
    ]
