# Generated by Django 5.0.1 on 2024-02-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sherly_app", "0032_alter_societe_boite_envoi_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bon_commande",
            name="axe_d",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="bon_commande",
            name="axe_g",
            field=models.IntegerField(),
        ),
    ]
