# Generated by Django 4.2.9 on 2024-02-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherly_app', '0033_alter_bon_commande_axe_d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bon_commande',
            name='axe_g',
            field=models.IntegerField(),
        ),
    ]
