# Generated by Django 5.0.1 on 2024-02-05 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sherly_app", "0033_alter_bon_commande_axe_d_alter_bon_commande_axe_g"),
        ("sherly_app", "0034_alter_bon_commande_axe_g"),
    ]

    operations = []
