# Generated by Django 4.2.9 on 2024-02-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherly_app', '0036_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='nif_facture',
            field=models.CharField(blank=True, default='NIF:B062835052-Nº IVA : ESB068350201152', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='societe',
            name='nif',
            field=models.CharField(blank=True, default='NIF:B062835052-Nº IVA : ESB068350201152', max_length=100, null=True),
        ),
    ]
