# Generated by Django 5.0.1 on 2024-02-05 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sherly_app", "0035_merge_20240205_2047"),
        ("sherly_app", "0037_alter_facture_nif_facture_alter_societe_nif"),
    ]

    operations = []
