# Generated by Django 5.0.1 on 2024-02-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sherly_app", "0038_merge_20240205_2105"),
    ]

    operations = [
        migrations.AddField(
            model_name="societe",
            name="pays",
            field=models.CharField(default="ESPAGNE", max_length=100),
        ),
        migrations.AddField(
            model_name="societe",
            name="telephone",
            field=models.CharField(default="+333333333333", max_length=100),
        ),
    ]
