# Generated by Django 5.0.1 on 2024-02-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sherly_app", "0039_societe_pays_societe_telephone"),
    ]

    operations = [
        migrations.AddField(
            model_name="facture",
            name="tva",
            field=models.IntegerField(default=0),
        ),
    ]
