# Generated by Django 5.0.1 on 2024-02-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sherly_app", "0041_societe_tva"),
    ]

    operations = [
        migrations.AddField(
            model_name="facture",
            name="paye1",
            field=models.CharField(
                blank=True, default="RIB :", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="facture",
            name="paye2",
            field=models.CharField(
                blank=True, default="IBAN :", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="facture",
            name="paye3",
            field=models.CharField(
                blank=True, default="BIC :", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="facture",
            name="phrase1",
            field=models.CharField(
                blank=True,
                default="Indemnité forfaitaire pour frais de recouvrement en cas de retard de paiement",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="facture",
            name="phrase2",
            field=models.CharField(
                blank=True,
                default="Pour effectuer le paiement, veuillez utiliser les informations bancaires suivantes :",
                max_length=150,
                null=True,
            ),
        ),
    ]
