# Generated by Django 5.0.1 on 2024-02-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sherly_app", "0043_alter_facture_facture1_alter_facture_facture2_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        default="DEFAULT_VALUE",
                        editable=False,
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("mois_concerne", models.CharField(max_length=7, unique=True)),
            ],
        ),
    ]
