# Generated by Django 5.0.1 on 2024-02-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sherly_app", "0046_emailsettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailsettings",
            name="email_host_password",
        ),
        migrations.RemoveField(
            model_name="emailsettings",
            name="email_host_user",
        ),
        migrations.AddField(
            model_name="emailsettings",
            name="DEFAULT_FROM_EMAIL",
            field=models.EmailField(
                default="sherylopticalstrategy@hotmail.com", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="emailsettings",
            name="EMAIL_BACKEND",
            field=models.CharField(
                default="django.core.mail.backends.smtp.EmailBackend", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="emailsettings",
            name="EMAIL_HOST",
            field=models.CharField(default="smtp.office365.com", max_length=100),
        ),
        migrations.AddField(
            model_name="emailsettings",
            name="EMAIL_PORT",
            field=models.IntegerField(default=587),
        ),
        migrations.AddField(
            model_name="emailsettings",
            name="EMAIL_USE_TLS",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="emailsettings",
            name="SERVER_EMAIL",
            field=models.EmailField(
                default="sherylopticalstrategy@hotmail.com", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="emailsettings",
            name="EMAIL_HOST_PASSWORD",
            field=models.CharField(default="vdqlnfmsvtwsusyf", max_length=100),
        ),
        migrations.AddField(
            model_name="emailsettings",
            name="EMAIL_HOST_USER",
            field=models.EmailField(
                default="sherylopticalstrategy@hotmail.com", max_length=254
            ),
        ),
    ]
