# Generated by Django 5.0.1 on 2024-02-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sherly_app", "0047_remove_emailsettings_email_host_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bon_livraison",
            name="t1c1",
            field=models.CharField(default="N<sup>o</sup> BL", max_length=100),
        ),
        migrations.AddField(
            model_name="bon_livraison",
            name="t1c2",
            field=models.CharField(default="DATE BL", max_length=100),
        ),
        migrations.AddField(
            model_name="bon_livraison",
            name="t1c3",
            field=models.CharField(default="N<sup>o</sup> CMDE", max_length=100),
        ),
        migrations.AddField(
            model_name="bon_livraison",
            name="t1c4",
            field=models.CharField(default="DATE CMDE", max_length=100),
        ),
        migrations.AddField(
            model_name="bon_livraison",
            name="t1c5",
            field=models.CharField(default="PORTEUR", max_length=100),
        ),
        migrations.AddField(
            model_name="bon_livraison",
            name="t1c6",
            field=models.CharField(default="CODE CLIENT", max_length=100),
        ),
        migrations.AddField(
            model_name="bon_livraison",
            name="t2c1",
            field=models.CharField(default="Référence", max_length=100),
        ),
        migrations.AddField(
            model_name="bon_livraison",
            name="t2c10",
            field=models.CharField(default="Qte", max_length=100),
        ),
        migrations.AddField(
            model_name="bon_livraison",
            name="t2c2",
            field=models.CharField(default="Désignation", max_length=100),
        ),
        migrations.AddField(
            model_name="bon_livraison",
            name="t2c3",
            field=models.CharField(default="Conditionnement", max_length=100),
        ),
        migrations.AddField(
            model_name="bon_livraison",
            name="t2c4",
            field=models.CharField(default="Diamètre", max_length=100),
        ),
        migrations.AddField(
            model_name="bon_livraison",
            name="t2c5",
            field=models.CharField(default="Rayon", max_length=100),
        ),
        migrations.AddField(
            model_name="bon_livraison",
            name="t2c6",
            field=models.CharField(default="Sphère", max_length=100),
        ),
        migrations.AddField(
            model_name="bon_livraison",
            name="t2c7",
            field=models.CharField(default="Cylindre", max_length=100),
        ),
        migrations.AddField(
            model_name="bon_livraison",
            name="t2c8",
            field=models.CharField(default="Axe", max_length=100),
        ),
        migrations.AddField(
            model_name="bon_livraison",
            name="t2c9",
            field=models.CharField(default="Oeil D/G", max_length=100),
        ),
    ]
