# Generated by Django 5.0.1 on 2024-02-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sherly_app", "0048_bon_livraison_t1c1_bon_livraison_t1c2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bon_livraison",
            name="t2c9",
            field=models.CharField(default="Oeil <br> D/G", max_length=100),
        ),
    ]
