# Generated by Django 5.0.1 on 2024-02-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sherly_app", "0049_alter_bon_livraison_t2c9"),
    ]

    operations = [
        migrations.CreateModel(
            name="TABLE_BL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("t1c1", models.CharField(default="N<sup>o</sup> BL", max_length=100)),
                ("t1c2", models.CharField(default="DATE BL", max_length=100)),
                (
                    "t1c3",
                    models.CharField(default="N<sup>o</sup> CMDE", max_length=100),
                ),
                ("t1c4", models.CharField(default="DATE CMDE", max_length=100)),
                ("t1c5", models.CharField(default="PORTEUR", max_length=100)),
                ("t1c6", models.CharField(default="CODE CLIENT", max_length=100)),
                ("t2c1", models.CharField(default="Référence", max_length=100)),
                ("t2c2", models.CharField(default="Désignation", max_length=100)),
                ("t2c3", models.CharField(default="Conditionnement", max_length=100)),
                ("t2c4", models.CharField(default="Diamètre", max_length=100)),
                ("t2c5", models.CharField(default="Rayon", max_length=100)),
                ("t2c6", models.CharField(default="Sphère", max_length=100)),
                ("t2c7", models.CharField(default="Cylindre", max_length=100)),
                ("t2c8", models.CharField(default="Axe", max_length=100)),
                ("t2c9", models.CharField(default="Oeil <br> D/G", max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="bon_livraison",
            name="t1c1",
        ),
        migrations.RemoveField(
            model_name="bon_livraison",
            name="t1c2",
        ),
        migrations.RemoveField(
            model_name="bon_livraison",
            name="t1c3",
        ),
        migrations.RemoveField(
            model_name="bon_livraison",
            name="t1c4",
        ),
        migrations.RemoveField(
            model_name="bon_livraison",
            name="t1c5",
        ),
        migrations.RemoveField(
            model_name="bon_livraison",
            name="t1c6",
        ),
        migrations.RemoveField(
            model_name="bon_livraison",
            name="t2c1",
        ),
        migrations.RemoveField(
            model_name="bon_livraison",
            name="t2c10",
        ),
        migrations.RemoveField(
            model_name="bon_livraison",
            name="t2c2",
        ),
        migrations.RemoveField(
            model_name="bon_livraison",
            name="t2c3",
        ),
        migrations.RemoveField(
            model_name="bon_livraison",
            name="t2c4",
        ),
        migrations.RemoveField(
            model_name="bon_livraison",
            name="t2c5",
        ),
        migrations.RemoveField(
            model_name="bon_livraison",
            name="t2c6",
        ),
        migrations.RemoveField(
            model_name="bon_livraison",
            name="t2c7",
        ),
        migrations.RemoveField(
            model_name="bon_livraison",
            name="t2c8",
        ),
        migrations.RemoveField(
            model_name="bon_livraison",
            name="t2c9",
        ),
    ]
