# Generated by Django 5.0.1 on 2024-02-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sherly_app", "0050_table_bl_remove_bon_livraison_t1c1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="table_bl",
            name="t2c10",
            field=models.CharField(default="Qté", max_length=100),
        ),
    ]
