# Generated by Django 5.0.1 on 2024-02-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sherly_app", "0053_alter_table_bl_t1c1_alter_table_bl_t1c3"),
    ]

    operations = [
        migrations.AddField(
            model_name="table_bl",
            name="date",
            field=models.CharField(default="DATE", max_length=100),
        ),
        migrations.AddField(
            model_name="table_bl",
            name="information_acheteur",
            field=models.CharField(default="INFORMATION ACHETEUR", max_length=100),
        ),
        migrations.AddField(
            model_name="table_bl",
            name="livre_a",
            field=models.CharField(default="LIVRE A", max_length=100),
        ),
    ]
