# Generated by Django 5.0.1 on 2024-02-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sherly_app", "0055_facture_date_facture_n_facture_facture_notice"),
    ]

    operations = [
        migrations.AddField(
            model_name="facture",
            name="facture_a",
            field=models.CharField(
                blank=True, default="FACTURE A", max_length=50, null=True
            ),
        ),
    ]
