# Generated by Django 5.0.1 on 2024-02-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sherly_app", "0056_facture_facture_a"),
    ]

    operations = [
        migrations.AddField(
            model_name="societe",
            name="pdf_pwd",
            field=models.CharField(default="Optical2024", max_length=20),
        ),
    ]
