# Generated by Django 5.0.1 on 2024-02-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sherly_app", "0057_societe_pdf_pwd"),
    ]

    operations = [
        migrations.AddField(
            model_name="bon_commande",
            name="add_d",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bon_commande",
            name="add_g",
            field=models.IntegerField(default=0),
        ),
    ]
