# Generated by Django 4.2.9 on 2025-06-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherly_app', '0061_produit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='famille',
            name='image',
            field=models.ImageField(blank=True, upload_to='familles/', verbose_name='Image'),
        ),
    ]
