# Generated by Django 4.2.9 on 2025-06-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherly_app', '0062_famille_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='famille',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
