# Generated by Django 4.2.9 on 2025-06-17 09:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherly_app', '0063_famille_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='famille',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
