# Generated by Django 5.0.1 on 2025-06-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_famille_date_creation_alter_produit_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(default='produits/default-product.jpg', upload_to='produits/', verbose_name='Image'),
        ),
    ]
