# Generated by Django 4.2.9 on 2025-06-16 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0003_alter_produit_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='prix',
        ),
    ]
