# Generated by Django 4.2.9 on 2025-06-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0004_remove_produit_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='famille',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
